### Get agent status
GET https://api.spacetraders.io/v2/my/agent
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



### View Contracts
GET https://api.spacetraders.io/v2/my/contracts
Content-Type: application/json
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



### View ships
GET https://api.spacetraders.io/v2/my/ships
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



### Negotiate a new contract
POST https://api.spacetraders.io/v2/my/ships/BRUMPO-3/negotiate/contract
Content-Type: application/json
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



### View Ship Cargo
GET https://api.spacetraders.io/v2/my/ships/BRUMPO-3/cargo
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



### View market for current pos
GET https://api.spacetraders.io/v2/systems/X1-MC9/waypoints/X1-MC9-A1/market
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



### Find nearby engineered asteroid
GET https://api.spacetraders.io/v2/systems/X1-MC9/waypoints?type=ENGINEERED_ASTEROID
Authorization: Bearer {{$dotenv BEARER_TOKEN}}



